from typing import Optional, Tuple

import torch
import triton
import triton.language as tl

flash_mla_sparse_fwd_configs = [
    triton.Config({"num_stages": 4, "num_warps": 8}),
    triton.Config({"num_stages": 2, "num_warps": 4}),
]


@triton.autotune(  # Decorate the kernel
    configs=flash_mla_sparse_fwd_configs,
    key=["K", "is_causal"],
)
@triton.jit
def triton_flash_mla_sparse_fwd(
    q,
    kv,
    indices,
    attn_sink,
    topk_length,
    sm_scale: tl.constexpr,
    output,
    max_logits,
    lse,
    stride_qh,
    stride_qm,
    stride_qd,
    stride_kvg,
    stride_kvn,
    stride_kvd,
    stride_tg,
    stride_tm,
    stride_tt,  # indices dim
    stride_attn_sink_h,
    stride_topk_length_s,
    stride_oh,
    stride_om,
    stride_od,
    stride_mh,
    stride_mm,
    stride_lh,
    stride_lm,
    SQ: tl.constexpr,  # seqlen
    SKV: tl.constexpr,  # seqlen_kv
    K: tl.constexpr,  # topk
    D: tl.constexpr,  # QKV dim
    TD: tl.constexpr,  # tail dim
    DP: tl.constexpr,
    TDP: tl.constexpr,
    G: tl.constexpr,  # group_size
    BK: tl.constexpr,
    BH: tl.constexpr,
    is_causal: tl.constexpr,
    q_idx_i64: tl.constexpr,
    output_idx_i64: tl.constexpr,
    HAVE_ATTN_SINK: tl.constexpr,
    HAVE_TOPK_LENGTH: tl.constexpr,
):
    i_sq, i_gbh = tl.program_id(0), tl.program_id(1)
    i_g, i_bh = i_gbh // G, i_gbh % G
    if not q_idx_i64:
        q_base = q + i_sq * stride_qm + i_gbh * (BH * stride_qh)
    else:
        q_base = q + i_sq * tl.cast(stride_qm, tl.int64) + i_gbh * (BH * stride_qh)
    tq_base = q_base + D * stride_qd
    kv_base = kv + i_g * stride_kvg
    tkv_base = kv_base + D * stride_kvd
    t_base = indices + i_sq * stride_tm + i_g * stride_tg
    attn_sink_ptr = (
        attn_sink + i_gbh * (BH * stride_attn_sink_h) if HAVE_ATTN_SINK else 0
    )
    topk_length_ptr = (
        topk_length + i_sq * stride_topk_length_s if HAVE_TOPK_LENGTH else 0
    )
    if not output_idx_i64:
        o_base = output + i_sq * stride_om + i_gbh * (BH * stride_oh)
    else:
        o_base = output + i_sq * tl.cast(stride_om, tl.int64) + i_gbh * (BH * stride_oh)
    max_log_base = max_logits + i_sq * stride_mm + i_gbh * (BH * stride_mh)
    l_base = lse + i_sq * stride_lm + i_gbh * (BH * stride_lh)

    offs_h = tl.arange(0, BH)
    offs_d = tl.arange(0, DP)
    offs_td = tl.arange(0, TDP) if TDP > 0 else None
    offs_od = tl.arange(0, DP)
    offs_t = tl.arange(0, BK)
    mask_h = i_bh * BH + offs_h < G
    mask_d = offs_d < D
    mask_td = offs_td < TD if TDP > 0 else None
    mask_od = mask_d

    q_ptr = q_base + offs_h[:, None] * stride_qh + offs_d[None, :] * stride_qd
    q_msk = mask_h[:, None] & mask_d[None, :]
    q_blk = tl.load(q_ptr, q_msk, other=0.0).to(tl.float32)

    tq_blk = None
    if TDP > 0:
        tq_ptr = tq_base + offs_h[:, None] * stride_qh + offs_td[None, :] * stride_qd
        tq_msk = mask_h[:, None] & mask_td[None, :]
        tq_blk = tl.load(tq_ptr, tq_msk, other=0.0).to(tl.float32)

    max_log = tl.full([BH], float("-inf"), dtype=tl.float32)
    sum_exp = tl.full([BH], 0.0, dtype=tl.float32)
    acc = tl.zeros([BH, DP], dtype=tl.float32)
    qk = tl.zeros([BH, BK], dtype=tl.float32)

    max_col = i_sq if is_causal else SKV - 1
    topk_len = tl.load(topk_length_ptr).to(tl.int32) if HAVE_TOPK_LENGTH else K

    NK = tl.cdiv(K, BK)
    for ck in range(NK):
        # step1: load indices
        t_ptr = (BK * ck + offs_t) * stride_tt
        t_msk = t_ptr < topk_len
        t_ptr += t_base
        kv_ids = tl.load(t_ptr, t_msk, other=-1)
        mask_ids = (kv_ids <= max_col) & (kv_ids >= 0)
        # filter invalid index that may cause overflow in mul
        kv_ids = tl.where(mask_ids, kv_ids, 0)

        # if mask_ids.max(0) > 0:
        if ck * BK <= max_col:
            # step2: gather kv with indices
            kv_ptr = (
                kv_base + offs_d[:, None] * stride_kvd + kv_ids[None, :] * stride_kvn
            )
            kv_msk = mask_d[:, None] & mask_ids[None, :]
            kv_blk = tl.load(kv_ptr, kv_msk, other=0.0).to(tl.float32)  # [DP, BK]

            # step3: (q @ kv) * sm_scale
            qk = tl.dot(q_blk, kv_blk)
            if TDP > 0:
                tkv_ptr = (
                    tkv_base
                    + offs_td[:, None] * stride_kvd
                    + kv_ids[None, :] * stride_kvn
                )
                tkv_msk = mask_td[:, None] & mask_ids[None, :]
                tkv_blk = tl.load(tkv_ptr, tkv_msk, other=0.0).to(
                    tl.float32
                )  # [TDP, BK]
                qk = tl.dot(tq_blk, tkv_blk, qk) * sm_scale
            else:
                qk = qk * sm_scale

            # step4: preprocess for logsumexp
            qk = tl.where(mask_ids[None, :], qk, float("-inf"))  # [BH, BK]
            # step5: lse=log2sumexp2(qk), loop part
            new_max = tl.maximum(max_log, tl.max(qk, axis=1))  # [BH]
            # avoid nan generated by ((-inf) - (-inf))
            tmp = qk - new_max[:, None]
            tmp = tl.where(
                (~mask_ids[None, :]) & (new_max[:, None] == float("-inf")),
                float("-inf"),
                tmp,
            )
            exp_qk = tl.math.exp(tmp)  # [BH, BK]
            sum_qk = tl.sum(exp_qk, axis=1)  # [BH]
            # avoid nan generated by ((-inf) - (-inf))
            tmp2 = max_log - new_max
            tmp2 = tl.where(
                (max_log == float("-inf")) & (new_max == float("-inf")),
                float("-inf"),
                tmp2,
            )
            alpha = tl.math.exp(tmp2)  # [BH]
            sum_exp = tl.fma(sum_exp, alpha, sum_qk)  # [BH]
            acc = acc * alpha[:, None]  # [BH, DP]
            # step6: exp2(qk-lse) @ gathered_kv.trans(), loop part
            acc = tl.dot(exp_qk, kv_blk.trans(), acc)  # [BH, DP]
            max_log = new_max

    # step7: store max_logits
    max_log_ptr = max_log_base + offs_h * stride_lh
    tl.store(max_log_ptr, max_log, mask_h)  # [BH], float32

    # step8: lse=log2sumexp2(qk) final part, store lse
    orig_lse = max_log + tl.math.log(sum_exp)
    lse_out = tl.where(orig_lse == float("-inf"), float("inf"), orig_lse)
    l_ptr = l_base + offs_h * stride_lh
    l_msk = mask_h
    tl.store(l_ptr, lse_out, l_msk)  # [BH], float32

    # step9: exp2(qk-lse) @ gathered_kv.trans(), final part
    if HAVE_ATTN_SINK:
        # step10: attn_sink
        exp_max_qk = tl.math.exp(max_log)  # [BH]
        exp_orig_lse = tl.math.exp(orig_lse)
        sink = tl.load(attn_sink_ptr + offs_h).to(tl.float32)  # [BH]
        exp_sink = tl.math.exp(sink)
        sum_exp_new_lse = exp_orig_lse + exp_sink
        # avoid divide 0
        sum_exp_new_lse = tl.where(sum_exp_new_lse == 0.0, 1.0, sum_exp_new_lse)
        factor = exp_max_qk / sum_exp_new_lse
        out_vals = acc * factor[:, None]
    else:
        # avoid divide 0
        sum_exp = tl.where(sum_exp == 0, 1.0, sum_exp)
        out_vals = acc / sum_exp[:, None]

    # step11: store output
    o_ptr = (
        o_base + offs_h[:, None] * stride_oh + offs_od[None, :] * stride_od
    )  # [BH, DP]
    o_msk = mask_h[:, None] & mask_od[None, :]
    tl.store(o_ptr, out_vals.to(q_blk.dtype), o_msk)


def flash_mla_sparse_fwd(
    q: torch.Tensor,
    kv: torch.Tensor,
    indices: torch.Tensor,
    sm_scale: float,
    d_v: int = 512,
    attn_sink: Optional[torch.Tensor] = None,
    topk_length: Optional[torch.Tensor] = None,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Sparse attention prefill kernel

    Args:
        q: [s_q, h_q, d_qk], bfloat16
        kv: [s_kv, h_kv, d_qk], bfloat16
        indices: [s_q, h_kv, topk], int32. Invalid indices should be set to -1 or numbers >= s_kv
        sm_scale: float
        d_v: The dimension of value vectors. Can only be 512
        attn_sink: optional, [h_q], float32.
            If attn_sink is provided, when computing output, output will be additionally multiplied by
            exp(lse) / (exp(lse) + exp(attn_sink)). +-inf in attn_sink will be handled normally (i.e., -inf has no
            effect, +inf will make corresponding output all zeros).
            This argument has no effect on lse and max_logits.
        topk_length: optional, [s_q], int32.
            If provided, the i-th q token will only attend to k tokens specified by indices[i, :, :topk_length[i]],
            ignoring later k/v tokens (even if provided in indices). In extremely rare cases (topk_length provided,
            there is a valid topk index between topk_length[i] ~ s_kv, and that topk index points to a k token
            containing NaN), operator output will contain NaN, so please avoid this situation.

    Returns:
        (output, max_logits, lse)
        Please refer to tests/ref.py for the precise definitions of these parameters.
        - output: [s_q, h_q, d_v], bfloat16
        - max_logits:  [s_q, h_q], float
        - lse: [s_q, h_q], float, log-sum-exp of attention scores
    """
    is_causal = False  # turn off opt for causal sparse attention
    assert q.is_contiguous() and kv.is_contiguous() and indices.is_contiguous()
    SQ, H, DT = q.shape
    SKV, VG, _ = kv.shape

    assert d_v == 512, "Unsupported d_v"
    D = d_v

    assert kv.shape[-1] == DT
    TD = DT - D
    DP = triton.next_power_of_2(D)
    TDP = triton.next_power_of_2(TD)
    _, _, K = indices.shape
    assert indices.shape == (SQ, VG, K)
    if attn_sink is not None:
        assert attn_sink.shape == (H,), "attn_sink error shape"
    if topk_length is not None:
        assert topk_length.shape == (SQ,), "topk_length error shape"

    # check from FlashMLA
    assert VG == 1, "h_kv is expected to be 1"
    assert H == 64 or H == 128, "Unsupported h_q"
    assert DT == 576 or DT == 512, "Unsupported d_qk"

    G = H // VG
    BH = max(16, min(32, triton.next_power_of_2(G)))
    NH = triton.cdiv(G, BH)
    BK = 16  # used to be out of memory for 32
    output = torch.zeros((SQ, H, D), device=q.device, dtype=q.dtype)
    max_logits = torch.full(
        (SQ, H), float("-inf"), device=q.device, dtype=torch.float32
    )
    lse = torch.full((SQ, H), float("-inf"), device=q.device, dtype=torch.float32)
    INT32_MAX = 2147483647
    q_idx_i64 = q.numel() > INT32_MAX
    output_idx_i64 = output.numel() > INT32_MAX
    grid = (SQ, VG * NH, 1)
    triton_flash_mla_sparse_fwd[grid](
        q,
        kv,
        indices,
        attn_sink,
        topk_length,
        sm_scale,
        output,
        max_logits,
        lse,
        q.stride(1),
        q.stride(0),
        q.stride(2),
        kv.stride(1),
        kv.stride(0),
        kv.stride(2),
        indices.stride(1),
        indices.stride(0),
        indices.stride(2),
        attn_sink.stride(0) if attn_sink is not None else 0,
        topk_length.stride(0) if topk_length is not None else 0,
        output.stride(1),
        output.stride(0),
        output.stride(2),
        max_logits.stride(1),
        max_logits.stride(0),
        lse.stride(1),
        lse.stride(0),
        SQ,
        SKV,
        K,
        D,
        TD,
        DP,
        TDP,
        G,
        BK,
        BH,
        is_causal,
        q_idx_i64,
        output_idx_i64,
        attn_sink is not None,
        topk_length is not None,
    )
    return output, max_logits, lse
