---
name: Backend Test

on:
  workflow_call:
    inputs:
      vendor:
        description: 'GEMS_VENDOR value (e.g. iluvatar, ascend, moore)'
        required: true
        type: string
      runner_label:
        description: 'GitHub Actions runner label'
        required: true
        type: string
      gpu_check_script:
        description: 'Path to GPU check script (leave empty to skip)'
        required: false
        type: string
        default: ''
      changed_files:
        description: 'List of changed files in a PR'
        required: false
        type: string
        default: ''
      pr_id:
        description: 'ID of the PR'
        required: false
        type: string
        default: ''
      test_script:
        description: "Temporary parameter for alpha-ops test"
        required: false
        type: string
        default: ''
    secrets:
      RUNNER_SSH_KEY:
        required: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ inputs.runner_label }}
    concurrency:
      group: >-
        op-test-${{ inputs.vendor }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Set global proxy
        shell: bash
        run: |
          echo "HTTP_PROXY=http://10.1.7.116:7890" >> $GITHUB_ENV
          echo "HTTPS_PROXY=http://10.1.7.116:7890" >> $GITHUB_ENV
      - uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.RUNNER_SSH_KEY }}
      - name: Check GPU availability
        if: ${{ inputs.gpu_check_script != '' }}
        shell: bash
        run: |
          bash ${{ inputs.gpu_check_script }}
      - name: Test alpha ops
        if: ${{ inputs.test_script != '' }}
        env:
          CHANGED_FILES: ${{ inputs.changed_files }}
        shell: bash
        run: |
          bash ${{ inputs.test_script }} ${{ inputs.vendor }} ${{ inputs.pr_id }}
      - name: Run backend tests
        if: ${{ inputs.test_script == '' }}
        env:
          CHANGED_FILES: ${{ inputs.changed_files }}
          HTTP_PROXY: http://10.1.12.38:38002
          HTTPS_PROXY: http://10.1.12.38:38002
        shell: bash
        run: |
          tools/test_backends.sh ${{ inputs.vendor }} ${{ inputs.pr_id }}
